/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.SelfSite;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelfSiteRecord extends UpdatableRecordImpl<SelfSiteRecord> implements Record19<Integer, Integer, String, String, String, String, Integer, LocalDateTime, String, String, Timestamp, BigDecimal, String, String, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 2138305473;

    /**
     * Setter for <code>nutch.self_site.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.self_site.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.self_site.position</code>. 地理位置ID
     */
    public void setPosition(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.self_site.position</code>. 地理位置ID
     */
    public Integer getPosition() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>nutch.self_site.url</code>. 信息页面地址
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.self_site.url</code>. 信息页面地址
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nutch.self_site.code</code>. ʡ
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.self_site.code</code>. ʡ
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.self_site.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.self_site.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nutch.self_site.category</code>.
     */
    public void setCategory(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>nutch.self_site.category</code>.
     */
    public String getCategory() {
        return (String) get(5);
    }

    /**
     * Setter for <code>nutch.self_site.order_index</code>.
     */
    public void setOrderIndex(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>nutch.self_site.order_index</code>.
     */
    public Integer getOrderIndex() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>nutch.self_site.fetch_time</code>. ץȡʱ
     */
    public void setFetchTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>nutch.self_site.fetch_time</code>. ץȡʱ
     */
    public LocalDateTime getFetchTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>nutch.self_site.text_value</code>.
     */
    public void setTextValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>nutch.self_site.text_value</code>.
     */
    public String getTextValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nutch.self_site.html_value</code>.
     */
    public void setHtmlValue(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>nutch.self_site.html_value</code>.
     */
    public String getHtmlValue() {
        return (String) get(9);
    }

    /**
     * Setter for <code>nutch.self_site.date_value</code>.
     */
    public void setDateValue(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>nutch.self_site.date_value</code>.
     */
    public Timestamp getDateValue() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>nutch.self_site.num_value</code>.
     */
    public void setNumValue(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>nutch.self_site.num_value</code>.
     */
    public BigDecimal getNumValue() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>nutch.self_site.server_num</code>.
     */
    public void setServerNum(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>nutch.self_site.server_num</code>.
     */
    public String getServerNum() {
        return (String) get(12);
    }

    /**
     * Setter for <code>nutch.self_site.domain</code>.
     */
    public void setDomain(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>nutch.self_site.domain</code>.
     */
    public String getDomain() {
        return (String) get(13);
    }

    /**
     * Setter for <code>nutch.self_site.url_id</code>.
     */
    public void setUrlId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>nutch.self_site.url_id</code>.
     */
    public Integer getUrlId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>nutch.self_site.location</code>.
     */
    public void setLocation(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>nutch.self_site.location</code>.
     */
    public String getLocation() {
        return (String) get(15);
    }

    /**
     * Setter for <code>nutch.self_site.description</code>. 摘要
     */
    public void setDescription(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>nutch.self_site.description</code>. 摘要
     */
    public String getDescription() {
        return (String) get(16);
    }

    /**
     * Setter for <code>nutch.self_site.mirror_url</code>. 镜像地址，原页面地址打不开时用
     */
    public void setMirrorUrl(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>nutch.self_site.mirror_url</code>. 镜像地址，原页面地址打不开时用
     */
    public String getMirrorUrl() {
        return (String) get(17);
    }

    /**
     * Setter for <code>nutch.self_site.class_id</code>. 1为招标，2为中标
     */
    public void setClassId(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>nutch.self_site.class_id</code>. 1为招标，2为中标
     */
    public Integer getClassId() {
        return (Integer) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, Integer, String, String, String, String, Integer, LocalDateTime, String, String, Timestamp, BigDecimal, String, String, Integer, String, String, String, Integer> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, Integer, String, String, String, String, Integer, LocalDateTime, String, String, Timestamp, BigDecimal, String, String, Integer, String, String, String, Integer> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelfSite.SELF_SITE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelfSite.SELF_SITE.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SelfSite.SELF_SITE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SelfSite.SELF_SITE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SelfSite.SELF_SITE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SelfSite.SELF_SITE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return SelfSite.SELF_SITE.ORDER_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return SelfSite.SELF_SITE.FETCH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SelfSite.SELF_SITE.TEXT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SelfSite.SELF_SITE.HTML_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return SelfSite.SELF_SITE.DATE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return SelfSite.SELF_SITE.NUM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SelfSite.SELF_SITE.SERVER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return SelfSite.SELF_SITE.DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return SelfSite.SELF_SITE.URL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return SelfSite.SELF_SITE.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return SelfSite.SELF_SITE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return SelfSite.SELF_SITE.MIRROR_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return SelfSite.SELF_SITE.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getOrderIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getFetchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTextValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getHtmlValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getDateValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getNumValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getServerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getUrlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getMirrorUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value2(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value3(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value6(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value7(Integer value) {
        setOrderIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value8(LocalDateTime value) {
        setFetchTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value9(String value) {
        setTextValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value10(String value) {
        setHtmlValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value11(Timestamp value) {
        setDateValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value12(BigDecimal value) {
        setNumValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value13(String value) {
        setServerNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value14(String value) {
        setDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value15(Integer value) {
        setUrlId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value16(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value17(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value18(String value) {
        setMirrorUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value19(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, Integer value7, LocalDateTime value8, String value9, String value10, Timestamp value11, BigDecimal value12, String value13, String value14, Integer value15, String value16, String value17, String value18, Integer value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelfSiteRecord
     */
    public SelfSiteRecord() {
        super(SelfSite.SELF_SITE);
    }

    /**
     * Create a detached, initialised SelfSiteRecord
     */
    public SelfSiteRecord(Integer id, Integer position, String url, String code, String name, String category, Integer orderIndex, LocalDateTime fetchTime, String textValue, String htmlValue, Timestamp dateValue, BigDecimal numValue, String serverNum, String domain, Integer urlId, String location, String description, String mirrorUrl, Integer classId) {
        super(SelfSite.SELF_SITE);

        set(0, id);
        set(1, position);
        set(2, url);
        set(3, code);
        set(4, name);
        set(5, category);
        set(6, orderIndex);
        set(7, fetchTime);
        set(8, textValue);
        set(9, htmlValue);
        set(10, dateValue);
        set(11, numValue);
        set(12, serverNum);
        set(13, domain);
        set(14, urlId);
        set(15, location);
        set(16, description);
        set(17, mirrorUrl);
        set(18, classId);
    }
}
