/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.User;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record15<Integer, String, String, String, String, String, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = -242228379;

    /**
     * Setter for <code>nutch.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.user.phonenum</code>.
     */
    public void setPhonenum(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.user.phonenum</code>.
     */
    public String getPhonenum() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nutch.user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nutch.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.user.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.user.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nutch.user.corporation</code>.
     */
    public void setCorporation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>nutch.user.corporation</code>.
     */
    public String getCorporation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>nutch.user.industry</code>.
     */
    public void setIndustry(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>nutch.user.industry</code>.
     */
    public Integer getIndustry() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>nutch.user.sites</code>.
     */
    public void setSites(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>nutch.user.sites</code>.
     */
    public String getSites() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nutch.user.keyword</code>.
     */
    public void setKeyword(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>nutch.user.keyword</code>.
     */
    public String getKeyword() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nutch.user.salt</code>.
     */
    public void setSalt(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>nutch.user.salt</code>.
     */
    public String getSalt() {
        return (String) get(9);
    }

    /**
     * Setter for <code>nutch.user.vip</code>.
     */
    public void setVip(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>nutch.user.vip</code>.
     */
    public Integer getVip() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>nutch.user.login_time</code>.
     */
    public void setLoginTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>nutch.user.login_time</code>.
     */
    public LocalDateTime getLoginTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>nutch.user.signup_time</code>.
     */
    public void setSignupTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>nutch.user.signup_time</code>.
     */
    public LocalDateTime getSignupTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>nutch.user.vip_end_time</code>.
     */
    public void setVipEndTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>nutch.user.vip_end_time</code>.
     */
    public LocalDateTime getVipEndTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>nutch.user.friend</code>.
     */
    public void setFriend(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>nutch.user.friend</code>.
     */
    public String getFriend() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, Integer, String, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.PHONENUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.CORPORATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return User.USER.INDUSTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.SITES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return User.USER.KEYWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return User.USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return User.USER.VIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return User.USER.LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return User.USER.SIGNUP_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return User.USER.VIP_END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return User.USER.FRIEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPhonenum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCorporation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSites();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getKeyword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getVip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getSignupTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getVipEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getFriend();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setPhonenum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setCorporation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Integer value) {
        setIndustry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setSites(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(String value) {
        setKeyword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(Integer value) {
        setVip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(LocalDateTime value) {
        setLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value13(LocalDateTime value) {
        setSignupTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value14(LocalDateTime value) {
        setVipEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value15(String value) {
        setFriend(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, String value9, String value10, Integer value11, LocalDateTime value12, LocalDateTime value13, LocalDateTime value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String phonenum, String username, String password, String email, String corporation, Integer industry, String sites, String keyword, String salt, Integer vip, LocalDateTime loginTime, LocalDateTime signupTime, LocalDateTime vipEndTime, String friend) {
        super(User.USER);

        set(0, id);
        set(1, phonenum);
        set(2, username);
        set(3, password);
        set(4, email);
        set(5, corporation);
        set(6, industry);
        set(7, sites);
        set(8, keyword);
        set(9, salt);
        set(10, vip);
        set(11, loginTime);
        set(12, signupTime);
        set(13, vipEndTime);
        set(14, friend);
    }
}
