/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Baobiaoorder implements Serializable {

    private static final long serialVersionUID = 548481104;

    private Integer       id;
    private Integer       userid;
    private String        outtradeno;
    private String        tradeno;
    private Double        amount;
    private LocalDateTime time;
    private Integer       status;
    private String        phonenum;

    public Baobiaoorder() {}

    public Baobiaoorder(Baobiaoorder value) {
        this.id = value.id;
        this.userid = value.userid;
        this.outtradeno = value.outtradeno;
        this.tradeno = value.tradeno;
        this.amount = value.amount;
        this.time = value.time;
        this.status = value.status;
        this.phonenum = value.phonenum;
    }

    public Baobiaoorder(
        Integer       id,
        Integer       userid,
        String        outtradeno,
        String        tradeno,
        Double        amount,
        LocalDateTime time,
        Integer       status,
        String        phonenum
    ) {
        this.id = id;
        this.userid = userid;
        this.outtradeno = outtradeno;
        this.tradeno = tradeno;
        this.amount = amount;
        this.time = time;
        this.status = status;
        this.phonenum = phonenum;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getOuttradeno() {
        return this.outtradeno;
    }

    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno;
    }

    public String getTradeno() {
        return this.tradeno;
    }

    public void setTradeno(String tradeno) {
        this.tradeno = tradeno;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public LocalDateTime getTime() {
        return this.time;
    }

    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getPhonenum() {
        return this.phonenum;
    }

    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Baobiaoorder (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(outtradeno);
        sb.append(", ").append(tradeno);
        sb.append(", ").append(amount);
        sb.append(", ").append(time);
        sb.append(", ").append(status);
        sb.append(", ").append(phonenum);

        sb.append(")");
        return sb.toString();
    }
}
